version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.1
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: marshmallow
    versions:
    - 3.11.0
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.6
