version: '2'

services:
  frontend:
    links:
      - db
    image: node:12.14.0-stretch
    expose:
      - 3000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh -t 25 backend:5000
      && npm install yarn && cd poker-client && yarn install && yarn start"

  backend:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_SCHEMA}"

